name: CI/CD Pipeline

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }} .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }}

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy ARM Template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: <Your_Subscription_Id>
        resourceGroupName: <Your_Resource_Group_Name>
        template: ./path/to/template.json
        parameters: |
          webAppName=shopnozama
          appServicePlanName=IDSFinal706
          location=EastUS
          dockerImage=${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }}
