name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install system dependencies for PyODBC
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends gnupg g++ unixodbc-dev curl

    - name: Add Microsoft repository key and repo for Debian 10 (Buster)
      run: |
        curl https://packages.microsoft.com/keys/microsoft.asc -o microsoft.asc
        sudo apt-key add microsoft.asc
        echo "deb [arch=amd64] https://packages.microsoft.com/debian/10/prod buster main" | sudo tee /etc/apt/sources.list.d/mssql-release.list

    - name: Install msodbcsql18
      run: |
        sudo apt-get update
        sudo ACCEPT_EULA=Y apt-get install -y --no-install-recommends msodbcsql18

    - name: Install Python dependencies
      run: pip install --no-cache-dir -r requirements.txt

    - name: Run tests
      env:
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: make test

